1. **列向量行向量**  np.array 产生的既不是行向量也不是列向量，它只是一个维度为(3,)的向量

In [2]:
import numpy as np

a = np.array([1,2,3])

display(a.shape)
display(a.T.shape)

(3,)

(3,)

In [47]:
#### 列向量正确的写法

b = a.reshape(3,1)  ## 或者写为b = a.reshape(-1,1)
display(b)
display(b.shape)
display(b.T)

for i in range(len(b)):
    print (i,b[i,:]+1)

array([[1],
       [2],
       [3]])

(3, 1)

array([[1, 2, 3]])

0 [2]
1 [3]
2 [4]


In [16]:
#### 行向量
b = a.reshape(1,3)  ## 或者写为b = a.reshape(1,-1)
display(b.shape)
display(b.T)

(1, 3)

array([[1],
       [2],
       [3]])

In [24]:
#### 用numpy.exp_dims(numpy.ndarray.axis)构造行向量或者列向量

## 行向量

b = np.expand_dims(a,axis=0)

display(b.shape)

## 列向量

b = np.expand_dims(a,axis=1)

display(b.shape)

(1, 3)

(3, 1)

2. **axis的理解**,axis对应的是shape的下标，若为0，则表示去掉第一个，对剩下的维度进行处理，如mean，则表示对列求均值，若为1，则表示去掉列，对行求均值

In [25]:
a = np.array([[1,2],[3,5]])
display(a)
a.shape

array([[1, 2],
       [3, 5]])

(2, 2)

In [26]:
np.mean(a)

2.75

In [27]:
np.mean(a,axis=0)

array([2. , 3.5])

In [28]:
np.mean(a,axis=1)

array([1.5, 4. ])

3.**矩阵合并**

In [33]:
## 按列合并
display(b)
c = np.array([4,5,6]).reshape(3,1)
display(c)


array([[1],
       [2],
       [3]])

array([[4],
       [5],
       [6]])

In [36]:
display(np.column_stack((b,c)))

display(np.hstack((b,c)))

array([[1, 4],
       [2, 5],
       [3, 6]])

array([[1, 4],
       [2, 5],
       [3, 6]])

In [37]:
## 按行合并
display(np.row_stack((b,c)))

display(np.vstack((b,c)))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

4. 矩阵乘法

In [51]:
a = np.array([1,2,3]).reshape(-1,1)

b = np.array([[1,2,3],[2,3,4]])

c = np.array([15,22]).reshape(-1,1)

c - np.dot(b,a)

array([[1],
       [2]])

In [56]:
a = np.array([1,2,3]).reshape(-1,1)

b = np.array([2,3,4]).reshape(-1,1)

display(a*b)

display(np.dot(a.T,b))

display(np.sum(a*b))

if np.dot(a.T,b) < 21:
    print ("haha")

array([[ 2],
       [ 6],
       [12]])

array([[20]])

20

haha


矩阵与向量

In [12]:
a = np.array([1,2,3])

b = np.array([2,3,4])

display(a)

display(b)


array([1, 2, 3])

array([2, 3, 4])

In [17]:
a.reshape((-1,1)).shape

(3, 1)

In [18]:
a*b

array([ 2,  6, 12])

In [19]:
np.dot(a,b)

20

In [15]:
np.mat(a).shape

(1, 3)

In [16]:
np.mat(a).T.shape

(3, 1)

In [22]:
np.mat(a)*np.mat(b).T  ## 注意比较与a*b的区别

matrix([[20]])

In [36]:
a = np.array([[1,2,3],[4,5,3]])
display(b.reshape(1,-1))
display(np.dot(a,b))
np.dot(a,b.reshape(1,-1))

array([[2, 3, 4]])

array([20, 35])

ValueError: shapes (2,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

In [11]:
np.zeros(3)

array([0., 0., 0.])